[unstable]
build-std = ["core", "compiler_builtins"] # Recompile the two libraries.
build-std-features = ["compiler-builtins-mem"] # Activate implementations that collides the C library.

[build]
target = "x86_64-blog_os.json"

# Specify the command should be invoked for 'cargo run'.
[target.'cfg(target_os = "none")']
runner = "bootimage runner"